version: '3.2'

services:

  soaenergybackend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 20081:8000
    volumes:
       # Re-use local composer cache via host-volume
      - ./:/app
    networks:
      - soaapi

      

  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Ubuxa##99
      - MYSQL_DATABASE=forge2
      - MYSQL_USER=forge2
      - MYSQL_PASSWORD=Ubuxa##99
    networks:
      - soaapi

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 6061:80
    environment:
      - PMA_HOST=mysql
      - PMA_PASSWORD=Ubuxa##99
    restart: unless-stopped
    volumes:
    - ./:/app
    networks:
      - soaapi
  
networks:
  soaapi:
    driver: bridge
