version: 2.1


jobs:
  deploy-prod:
    docker:
        - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
         fingerprints: 
          - "94:f3:79:6d:db:f2:27:8e:98:e2:7f:30:bb:da:5c:03"
      - checkout
      # install dependencies
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: CI=false yarn install
      - run:
          name: update apt-get
          command: CI=false sudo apt-get update
      - run:
          name: rename .env.example file to .env 
          command: |
            CI=false mv .env.example .env
      - run:
          name: find and replace default path
          command: |
            CI=false sed -i -e 's|https://devapi.soaenergy.com/api|https:saoenergy.skillzserver.com/api|g' .env && sed -i -e 's|https://dev.soaenergy.com|https://admin.soaenergy.com|g' .env


      - run:
          name: build and push 
          command: CI=false yarn build
      - run:
          name: Install  rsync 
          command: CI=false sudo apt-get install -y rsync
      - run:
          name: Update known hosts
          command: CI=false ssh-keyscan -H 66.29.151.25 >> ~/.ssh/known_hosts
      
      - run:
          name: ssh login  
          command: |
            CI=false rsync -va -e 'ssh -vvv -p 7822 -o StrictHostKeyChecking=no' --delete dist/ .htaccess skillz@185.160.67.60:saoenergyadmin.skillzserver.com
    #   - run:
    #       name: Directory Listing  
    #       command: ls

  deploy-dev:
    docker:
        - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
         fingerprints: 
          - "eb:a6:7b:a1:6a:f4:34:73:95:02:9e:86:ee:15:a0:ed"
      - checkout
      # install dependencies
      - setup_remote_docker:
          version: 20.10.12
          docker_layer_caching: true

      - run:
          name: update apt-get
          command: CI=false sudo apt-get update
      - run:
          name: Install dependencies
          command: CI=false yarn install
      - run:
          name: rename .env.example file to .env 
          command: |
            CI=false mv .env.example .env

      - run:
          name: build and push 
          command: CI=false yarn build
      - run:
          name: Install  rsync 
          command: CI=false sudo apt-get install -y rsync
      - run:
          name: Update known hosts
          command: CI=false ssh-keyscan -H 66.29.151.25 >> ~/.ssh/known_hosts

      - run:
          name: ssh login  
          command: |
            CI=false rsync -va -e 'ssh -p 21 -o StrictHostKeyChecking=no' --delete dist/ .htaccess saoenergy@saoenergy.com:dev.saoenergy.com
      - run:
          name: Directory Listing  
          command: CI=false ls
workflows:
  version: 2
  Barm_deploy:
    jobs:
      - deploy-dev: # Use the pre-configured job, deploy-via-git
          filters:
            branches:
              only: dev1
      - deploy-prod: # Use the pre-configured job, deploy-via-git
          filters:
            branches:
              only: init