name: sao_deploy_frontend_prod

# on:
  
#   pull_request:
#     branches:
#       - prod
#     types: [closed]

on:
  push:
jobs:
  deploy-sao-frontend-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: cd frontend && yarn install

      - name: Build Project
        run: cd frontend && yarn build
      
      - name: SSH login
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY_PROD}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync --delete --exclude 'api' -va -e 'ssh  -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no' \
            frontend/dist/ frontend/.htaccess saoenergyco@saoenergy.co.uk:www

      
      
      